---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  ignore_errors: yes

- name: Ensure PHP packages are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items: php_packages
  notify: restart webserver
