---
# In order to install/update contrib module, run followign command from root of project:
#        ansible-galaxy install -n -f -r contrib/requirements.yml
#
# Contrib requirements list.
#
- src: https://github.com/cibox/ansible-composer
  path: contrib

- src: https://github.com/cibox/ansible-php-pear
  path: contrib

- src: https://github.com/geerlingguy/ansible-role-apache
  version: 1.5.0
  path: contrib

- src: https://github.com/geerlingguy/ansible-role-memcached
  version: 1.0.2
  path: contrib

- src: https://github.com/geerlingguy/ansible-role-mysql
  version: 1.5.0
  path: contrib

- src: https://github.com/geerlingguy/ansible-role-php
  version: 1.4.3
  path: contrib

- src: https://github.com/geerlingguy/ansible-role-php-pecl
  version: 1.2.1
  path: contrib

- src: https://github.com/geerlingguy/ansible-role-php-xdebug
  version: 1.1.3
  path: contrib

- src: https://github.com/geerlingguy/ansible-role-php-xhprof
  version: 1.0.0
  path: contrib
