---
# This playbook should be executed using 
# ansible-playbook jenkinsbox.yml
# command
# Developed for ansible version >= 1.7
- hosts: localvm
  # connection: local
  gather_facts: no
  remote_user: root

  roles:
    - { role: cibox-swap, tags: ["cibox-swap"], when: ansible_virtualization_type != "openvz" }
    - { role: ansible-php-pear, tags: ["ansible-php-pear", "php-stack"] }
    - { role: ansible-role-php-xhprof, tags: ["ansible-php-xhprof", "php-stack"] }
    - { role: ansible-composer, tags: ["ansible-composer", "php-stack"] }
    - { role: ansible-role-mysql, tags: ["mysql", "php-stack", "ansible-role-mysql"] }
    - { role: cibox-jenkins, tags: ["cibox-jenkins"] }
    - { role: cibox-jetty-solr, tags: ["cibox-jetty-solr"] }
    - { role: cibox-sniffers, tags: ["cibox-sniffers", "php-stack"] }
    - { role: cibox-mysql-config, tags: ["mysql", "php-stack", "cibox-mysql-config"] }
    - { role: cibox-ssl-config, tags: ["apache", "php-stack", "ssl", "cibox-ssl-config"] }
    - { role: cibox-behat-selenium2, tags: ["cibox-behat-selenium", "behat-selenium"] }

  vars_prompt:
    jenkins_user: "Enter linux root user username that will be used as superuser in jenkins UI"
    jenkins_pass: "Enter linux root user pass that will be used as superuser in jenkins UI"
  vars:
    # We are using unix pam autentification module for jenkins.
    plugins:
      - 'ansicolor'
      - 'credentials'
      - 'git-client'
      - 'git'
      - 'github-api'
      - 'github'
      - 'ghprb'
      - 'htmlpublisher'
      - 'jquery'
      - 'matrix-auth'
      - 'matrix-project'
      - 'php'
      - 'project-description-setter'
      - 'ssh-credentials'
      - 'hipchat'
      - 'scripttrigger'
      - 'parameterized-trigger'
    # @todo not uset yet
    project_name: CHANGE_ME
    # @todo not uset yet
    project_url: https://github.com/podarok/{{ project_name }}
    # @todo not uset yet
    project_repo_url: https://github.com/podarok/{{ project_name }}.git
    # Delay before jenkins up and running. Sometimes it is not enouph.
    startup_delay_s: 40
    pear_channels:
      - pear.drush.org
    pear_packages:
      - drush/drush
    apt_repos:
      - ppa:ansible/ansible
    apt_packages:
      - software-properties-common
      - python-software-properties
      - apparmor-utils
      - make
      - rsync
      - libssl-dev
      - zlib1g-dev
      - apache2
      - php5
      - php5-gd
      - php5-mcrypt
      - libapache2-mod-php5
      - php5-mysql
      - php5-curl
      - php5-memcached
      - memcached
      - tree
      - php5-imagick
      - imagemagick
      - ansible
      - git
      - imagemagick
      - php5-imagick
      - rng-tools
      - python-passlib
      - cgroup-bin
    apache2_modules:
      - rewrite
    jenkins_configs:
      - jenkins.model.JenkinsLocationConfiguration.xml
      - org.jenkinsci.plugins.ghprb.GhprbTrigger.xml
      - jobs/{{ project_name }}_PR_BUILDER/config.xml
    backup_folder: /var/www/backup
    backup_folder_user: propeople
    backup_folder_pass: givemebackup
    cibox_ssl_enable_host: true

  pre_tasks:
  - name: Setup initial packages onto clean system for ansible
    sudo: yes
    # Installing sudo on small ubuntu install.
    raw: "apt-get -y install python-simplejson sudo curl"

  - name: Fixing logger not found
    sudo: yes
    shell: "apt-get --reinstall install -y bsdutils"

  - name: Setup - get environment data for later usage
    setup:
    register: allmy
    tags:
      - cibox-jenkins

  - name: Adding jenkins user to group shadow
    user: name=jenkins groups=shadow append=yes
    tags:
      - cibox-jenkins

  - name: Adding jenkins user to group adm
    user: name=jenkins groups=adm append=yes
    tags:
      - cibox-jenkins

  - name: Adding jenkins user to nopasswd sudoers
    lineinfile: dest=/etc/sudoers line="jenkins ALL=(ALL) NOPASSWD:ALL"
    tags:
      - cibox-jenkins

  - name: Install apt repos
    apt_repository: repo={{ item }} validate_certs=no
    with_items: apt_repos
    tags:
      - php-stack
      - mysql
      - apache

  - name: Update apt cache
    sudo: yes
    apt: update_cache=yes
    ignore_errors: yes
    tags:
      - php-stack
      - mysql
      - apache

  - name: Install apt packages
    apt: name={{ item }} state=present
    with_items: apt_packages
    tags:
      - php-stack
      - mysql
      - apache

    # We have to disable mail sending from CI box.
    # Does not create a link if sendmail is installed.
  - name: Check for sendmail.
    file: path=/usr/sbin/sendmail src=/bin/true state=link force=no
    tags:
      - php-stack
      - mysql
      - apache

  - name: Create ansible config directory
    sudo: yes
    file: path=/etc/ansible state=directory mode=775
    tags:
      - php-stack
      - mysql
      - apache

  tasks:
    # @todo More smart way to upload jobs. Move job names to options.
  - name: Check if job already renamed.
    stat: path=/var/lib/jenkins/jobs/{{ project_name }}_PR_BUILDER
    register: prbuilder_stat
    tags:
      - cibox-jenkins

  - name: Copy local files for enabling jenkins permissions
    sudo: yes
    synchronize: src=files/jenkins/ dest=/var/lib/jenkins recursive=yes archive=no
    when: prbuilder_stat.stat.exists == false
    tags:
      - cibox-jenkins

  - name: Change owner for jenkins files.
    file: path=/var/lib/jenkins owner=jenkins group=jenkins force=yes recurse=yes state=directory
    tags:
      - cibox-jenkins

  - name: Rename jenkins jobs to meet project name.
    sudo: yes
    shell: "mv /var/lib/jenkins/jobs/PR_BUILDER /var/lib/jenkins/jobs/{{ project_name }}_PR_BUILDER"
    when: prbuilder_stat.stat.exists == false
    tags:
      - cibox-jenkins

  - name: Remove PR_BUILDER from remote.
    sudo: yes
    file: path=/var/lib/jenkins/jobs/PR_BUILDER state=absent
    when: prbuilder_stat.stat.exists == true
    tags:
      - cibox-jenkins
    # end of @todo More smart way to upload jobs. Move job names to options.

  - name: Change host IP address in jenkins configs
    replace: dest=/var/lib/jenkins/{{ item }} regexp='ci_server_ip_address' replace={{ allmy.ansible_facts.ansible_default_ipv4.address }}
    with_items: jenkins_configs
    tags:
      - cibox-jenkins

  - name: apt-get update
    apt: update_cache=yes
    ignore_errors: yes
    tags:
      - php-stack
      - mysql
      - apache

  - name: Apache2 modules
    apache2_module: state=present name={{ item }}
    with_items: apache2_modules
    tags:
      - apache
      - php-stack
    notify: Restart apache

  - name: Copy apache vhost file
    synchronize: src=files/sites-enabled/000-default.conf dest=/etc/apache2/sites-enabled/000-default.conf
    sudo: yes
    tags:
      - apache
      - php-stack
    notify: Restart apache

  - name: Starting random rnd-tools service
    sudo: yes
    shell: rngd -r /dev/urandom
    when: ansible_virtualization_type != "openvz"

  - name: Create backup folder
    file: path={{ backup_folder }} owner=www-data group=jenkins state=directory

  - name: Copy .htaccess to the backup folder
    synchronize: src=files/backup-folder/.htaccess dest={{ backup_folder }}/.htaccess

  - name: Generate .htpasswd
    htpasswd: path={{ backup_folder }}/.htpasswd name={{ backup_folder_user }} password={{ backup_folder_pass }}

  handlers:
  - name: Restart apache
    service: name=apache2 state=restarted
    tags:
      - mysql
      - apache
      - php-stack
