---
# This playbook should be executed using
# ansible-playbook jenkinsbox.yml
# command
# Developed for ansible version >= 1.7
#- hosts: test

- hosts: CHANGE_ME_TO_THE_ONE_FROM_hosts_FILEgi
  # connection: local
  gather_facts: yes
  remote_user: root

  roles:
    - ansible-behat-selenium2
    - ansible-php-pear
    - ansible-composer
    - ansible-jenkins
    - ansible-jetty-solr
    - ansible-sniffers

  vars_prompt:
    jenkins_user: "Enter linux root user username that will be used as superuser in jenkins UI"
    jenkins_pass: "Enter linux root user pass that will be used as superuser in jenkins UI"
  vars:
    # This should be a parameter 'count' for unix 'dd' command
    # See http://druler.com/node/860 for additional instructions.
    swap_size: 100M
    swap_blocks: 24
    # We are using unix pam autentification module for jenkins.
    plugins:
      - 'ansicolor'
      - 'credentials'
      - 'git-client'
      - 'git'
      - 'github-api'
      - 'github'
      - 'ghprb'
      - 'htmlpublisher'
      - 'jquery'
      - 'matrix-auth'
      - 'matrix-project'
      - 'php'
      - 'project-description-setter'
      - 'ssh-credentials'
      - 'hipchat'
    # @todo not uset yet
    project_name: CHANGE_ME
    # @todo not uset yet
    project_url: https://github.com/podarok/{{ project_name }}
    # @todo not uset yet
    project_repo_url: https://github.com/podarok/{{ project_name }}.git
    # Delay before jenkins up and running. Sometimes it is not enouph.
    startup_delay_s: 40
    pear_channels:
      - pear.drush.org
    pear_packages:
      - drush/drush
    apt_repos:
      - ppa:ansible/ansible
    apt_packages:
      - software-properties-common
      - python-software-properties
      - libssl-dev
      - zlib1g-dev
      - apache2
      - mysql-server
      - mysql-client
      - python-mysqldb
      - php5
      - php5-gd
      - php5-mcrypt
      - libapache2-mod-php5
      - php5-mysql
      - php5-curl
      - tree
      - php5-imagick
      - imagemagick
      - ansible
      - git
    apache2_modules:
      - rewrite
    jenkins_configs:
      - jenkins.model.JenkinsLocationConfiguration.xml
      - org.jenkinsci.plugins.ghprb.GhprbTrigger.xml
      - jobs/{{ project_name }}_PR_BUILDER/config.xml

  pre_tasks:
  - name: Setup - get environment data for later usage
    setup:
    register: allmy
    tags:
      - jenkins_jobs

  - name: Check if swap already enabled.
    sudo: yes
    file: path=/swapfile1 state=touch
    register: is_swapfile

  - name: Create swapfile if not present
    sudo: yes
    shell: 'dd if=/dev/zero of=/swapfile1 bs={{ swap_size }} count={{ swap_blocks }}'
    when: is_swapfile.changed == true and is_swapfile.size == 0

  - name: Make swapfile as swap
    sudo: yes
    shell: 'mkswap /swapfile1'
    when: is_swapfile.size != 0

  - name: Check if swap enabled as swapon
    sudo: yes
    shell: 'swapon -s'
    register: swapon

  - name: Enable swap
    sudo: yes
    shell: 'swapon /swapfile1'
    when: is_swapfile.size != 0 and swapon.stdout.find('swapfile1') == -1

  - name: Add swap to fstab
    sudo: yes
    mount: name=swap src=/swapfile1 fstype=swap opts=default state=present
    when: is_swapfile.size != 0

  - name: Adding jenkins user to group shadow
    user: name=jenkins groups=shadow append=yes

  - name: Adding jenkins user to group adm
    user: name=jenkins groups=adm append=yes

  - name: Adding jenkins user to nopasswd sudoers
    lineinfile: dest=/etc/sudoers line="jenkins ALL=(ALL) NOPASSWD:ALL"

  - name: Install apt repos
    apt_repository: repo={{ item }}
    with_items: apt_repos

  - name: Update apt cache
    sudo: yes
    apt: update_cache=yes
    ignore_errors: yes

  - name: Install apt packages
    apt: name={{ item }} state=present
    with_items: apt_packages

    # We have to disable mail sending from CI box.
    # Does not create a link if sendmail is installed.
  - name: Check for sendmail.
    file: path=/usr/sbin/sendmail src=/bin/true state=link force=no


    # @todo More smart way to upload jobs. Move job names to options.
  - name: Check if job already renamed.
    stat: path=/var/lib/jenkins/jobs/{{ project_name }}_PR_BUILDER
    register: prbuilder_stat
    tags:
      - jenkins_jobs

  - name: Copy local files for enabling jenkins permissions
    sudo: yes
    synchronize: src=files/jenkins/ dest=/var/lib/jenkins recursive=yes archive=no
    when: prbuilder_stat.stat.exists == false
    tags:
      - jenkins_jobs

  - name: Change owner for jenkins files.
    file: path=/var/lib/jenkins owner=jenkins group=jenkins force=yes recurse=yes state=directory
    tags:
      - jenkins_jobs

  - name: Rename jenkins jobs to meet project name.
    sudo: yes
    shell: "mv /var/lib/jenkins/jobs/PR_BUILDER /var/lib/jenkins/jobs/{{ project_name }}_PR_BUILDER"
    when: prbuilder_stat.stat.exists == false
    tags:
      - jenkins_jobs

  - name: Remove PR_BUILDER from remote.
    sudo: yes
    file: path=/var/lib/jenkins/jobs/PR_BUILDER state=absent
    when: prbuilder_stat.stat.exists == true
    tags:
      - jenkins_jobs
    # end of @todo More smart way to upload jobs. Move job names to options.

  - name: Change host IP address in jenkins configs
    replace: dest=/var/lib/jenkins/{{ item }} regexp='ci_server_ip_address' replace={{ allmy.ansible_facts.ansible_default_ipv4.address }}
    with_items: jenkins_configs
    tags:
      - jenkins_jobs

  - name: Create ansible config directory
    sudo: yes
    file: path=/etc/ansible state=directory mode=775

  tasks:
  - name: apt-get update
    apt: update_cache=yes
    ignore_errors: yes
    tags:
      - lamp

  - name: Apache2 modules
    apache2_module: state=present name={{ item }}
    with_items: apache2_modules
    tags:
      - apache
      - lamp
    notify: Restart apache

  - name: Copy apache vhost file
    synchronize: src=files/sites-enabled/000-default.conf dest=/etc/apache2/sites-enabled/000-default.conf
    sudo: yes
    tags:
      - apache
    notify: Restart apache

  - name: Add's to my.cnf file
    lineinfile: dest=/etc/mysql/my.cnf line="innodb_lock_wait_timeout = 900"
    sudo: yes
    tags:
      - mysql
    notify: Restart mysql

  handlers:
  - name: Restart apache
    service: name=apache2 state=restarted
  - name: Restart mysql
    service: name=mysql state=restarted
