---
behat_selenium2_dependencies:
  - xfonts-100dpi
  - xfonts-75dpi
  - xfonts-scalable
  - xfonts-cyrillic
  - xvfb
  - x11-apps
  - xserver-xorg-core
  - imagemagick
  - firefox
  - google-chrome-stable
  - unzip
  - tar
