---
# Add Jenkins repository
- include: repo.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

# Install dependencies
- include: dependencies_deb.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

# Download Jenkins package
- name: Download Jenkins deb
  get_url: url={{ jenkins_pkg_version }} dest=~/jenkins.deb mode=440
  sudo: yes

# Install Jenkins
- name: Install Jenkins
  sudo: yes
  shell: "dpkg -i ~/jenkins.deb"
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]
  register: jenkins_install

# Install Jenkins cli
- include: cli.yml

# Install/update Jenkins plugins
- include: plugins.yml

# Copy configs, jobs and users.
- include: configs.yml
