---
- name: Install PECL libaries.
  command: "pecl install {{ item }}"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  with_items: php_pecl_extensions

- name: Enable needed extensions
  lineinfile: line="extension={{ item }}.so" dest=/etc/php5/conf.d/20-pecl.ini create=yes
  with_items: php_pecl_extensions
