---
global_env:
  # Protecting against HTTP HOST Header attacks (https://www.drupal.org/node/1992030).
  trusted_host_patterns: []
  pre_settings: []
  modules: []
  drush_commands: []
  post_settings:
    - { name: '$settings["pp_environment"]', status: true, value: "{{ pp_environment }}" }
