---
# This script contains commands to run drush commands that are specified in configuration.
- name: Run general drush commands
  shell: "{{ php_env_vars }} drush -y {{ item.name }} {{ item.arguments }}"
  when: item.status == true
  loop: global_env.drush_commands

- name: Run environment specific drush commands
  shell: "{{ php_env_vars }} drush -y {{ item.name }} {{ item.arguments }}"
  when: item.status == true
  loop: env.drush_commands
