---
# This script contains commands to enable modules that are specified in configuration.
- name: Enable general modules
  shell: "{{ php_env_vars }} drush -y en {{ item.name }} -l {{ site_url }}"
  when: item.status == true
  with_items: global_env.modules

- name: Enable environment specific modules
  shell: "{{ php_env_vars }} drush -y en {{ item.name }} -l {{ site_url }}"
  when: item.status == true
  with_items: env.modules
