---
- name: Update apt
  apt: update_cache=yes
  sudo: yes

- name: Install packages
  action: apt pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - imagemagick
    - libmagickcore-dev
    - libmagickwand-dev
    - htop
    - vim
