---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure dependencies for building from source are installed (RedHat).
  yum: "name={{ item }} state=installed"
  with_items:
    - '@development'
  when: ansible_os_family == 'RedHat'

- name: Ensure dependencies for building from source are installed (Debian).
  apt: "name={{ item }} state=installed"
  with_items:
    - build-essential
  when: ansible_os_family == 'Debian'

- name: Untar Xdebug.
  unarchive:
    src: "https://xdebug.org/files/xdebug-{{ php_xdebug_version }}.tgz"
    dest: "{{ workspace }}"
    copy: no

- name: Build Xdebug.
  shell: >
    {{ item }}
    chdir={{ workspace }}/xdebug-{{ php_xdebug_version }}
    creates={{ workspace }}/xdebug-{{ php_xdebug_version }}/modules/xdebug.so
  with_items:
    - phpize
    - ./configure
    - make
  notify: restart webserver

- name: Ensure Xdebug module path exists.
  file:
    path: "{{ php_xdebug_module_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Move Xdebug module into place.
  shell: >
    cp {{ workspace }}/xdebug-{{ php_xdebug_version }}/modules/xdebug.so {{ php_xdebug_module_path }}/xdebug.so
    creates={{ php_xdebug_module_path }}/xdebug.so
  notify: restart webserver

- include: configure.yml
