---
# This playbook should be executed using 
# ansible-playbook jenkinsbox.yml
# command
# Developed for ansible version >= 1.7
# drupal subfolder with repo_subfolder name will be prepared after execution.

- hosts: 127.0.0.1
  connection: local
  gather_facts: no

  roles:

  vars:
    repo_subfolder: DEMO # name of the future project, should be changed manually
    drupal_subfolder: drupal
    installation_profile_name: pp
    drupal_version: 7
    with_vm: True
    with_reinstall: True
    vm_provisioner: puppet

  pre_tasks:

  - name: Creating project folder
    shell: "mkdir {{ repo_subfolder }} || true"

  - name: Creating drupal folder
    file: path={{ repo_subfolder }}/{{ drupal_subfolder }} state=directory
    register: drupal_stat

  - name: Downloading drupal to drupal subfolder
    shell: "cd {{ repo_subfolder }} && /usr/bin/drush -y --drupal-project-rename dl {{ drupal_subfolder }}"
    when: drupal_stat.changed == True
    register: drupal_dl

  - name: Inject pp profile into drupal
    file: path={{ repo_subfolder }}/{{ drupal_subfolder }}/profiles/{{ installation_profile_name }} state=directory
    register: is_profile

  - name: Copy local profile files to drupal directory
    synchronize: src=files/drupal{{ drupal_version }}/profiles/{{ installation_profile_name }}/ dest={{ repo_subfolder }}/{{ drupal_subfolder }}/profiles/{{ installation_profile_name }}/ recursive=yes archive=no
    register: profile_copy

  - name: Create folder placeholders for sniffers 1
    shell: "mkdir {{ repo_subfolder }}/{{ drupal_subfolder }}/sites/all/modules/custom/"
    ignore_errors: yes

  - name: Create folder placeholders for sniffers 2
    shell: "mkdir {{ repo_subfolder }}/{{ drupal_subfolder }}/sites/all/modules/contrib"
    ignore_errors: yes

  - name: Create folder placeholders for sniffers 3
    shell: "mkdir {{ repo_subfolder }}/{{ drupal_subfolder }}/sites/all/themes/custom/"
    ignore_errors: yes

  - name: Create folder placeholders for sniffers 4
    shell: "mkdir {{ repo_subfolder }}/{{ drupal_subfolder }}/sites/all/themes/contrib/"
    ignore_errors: yes

  - name: Create folder placeholders for sniffers 5
    shell: "mkdir {{ repo_subfolder }}/{{ drupal_subfolder }}/sites/all/modules/features"
    ignore_errors: yes

  - name: Create empty readme files for placeholders 1
    file: path={{ repo_subfolder }}/{{ drupal_subfolder }}/sites/all/modules/custom/readme.txt state=touch

  - name: Create empty readme files for placeholders 2
    file: path={{ repo_subfolder }}/{{ drupal_subfolder }}/sites/all/modules/contrib/readme.txt state=touch

  - name: Create empty readme files for placeholders 3
    file: path={{ repo_subfolder }}/{{ drupal_subfolder }}/sites/all/themes/custom/readme.txt state=touch

  - name: Create empty readme files for placeholders 4
    file: path={{ repo_subfolder }}/{{ drupal_subfolder }}/sites/all/themes/contrib/readme.txt state=touch

  - name: Create empty readme files for placeholders 5
    file: path={{ repo_subfolder }}/{{ drupal_subfolder }}/sites/all/modules/features/readme.txt state=touch

  - name: Injecting vmbox into repo
    synchronize: src=files/vagrant/{{ vm_provisioner }}/ dest={{ repo_subfolder }}/ recursive=yes archive=no
    when: with_vm == True
    register: vmbox

  - name: Add ansible roles to vagrant box
    synchronize: src=../roles/ dest={{ repo_subfolder }}/puphpet/ansible/roles/ recursive=yes archive=no
    when: with_vm == True
    register: vmbox

  - name: Copying installation scripts - reinstall.sh and playbook reinstall.yml
    synchronize: src=files/drupal{{ drupal_version }}/scripts/ dest={{ repo_subfolder }}/{{ drupal_subfolder }}/ recursive=yes archive=no
    when: with_reinstall == True

  - name: Setting permissions for drupal tree
    file: path={{ repo_subfolder }} state=directory mode=777 recurse=yes
    when: drupal_dl.changed == True or profile_copy.changed == True or vmbox.changed == True

  - name: Unsetting inventory file executable bit
    file: path={{ repo_subfolder }}/{{ drupal_subfolder }}/hosts mode=666
    when: with_reinstall == True

  handlers:
