---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Install and configure XHProf.
- name: Install XHProf using PECL.
  command: "pecl install {{ item }}"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  with_items:
    # Manual channel installation required for certain PEAR versions.
    - "channel://pecl.php.net/xhprof-0.9.4"
    - xhprof

- name: Ensure PHP configuration directories exist.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items: php_xhprof_config_dirs

- name: Copy XHProf INI into various other conf folders.
  template:
    src: xhprof.ini.j2
    dest: "{{ item }}/{{ php_xhprof_config_filename }}"
    owner: root
    group: root
    mode: 0644
  with_items: php_xhprof_config_dirs
  notify: restart webserver

- name: Ensure XHProf output directory exists.
  file:
    path: "{{ xhprof_output_dir }}"
    state: directory
    mode: 0777
