---
- name: Add packagecloud.io Varnish apt key.
  apt_key:
    url: https://packagecloud.io/varnishcache/varnish30/gpgkey
    state: present

- name: Add packagecloud.io Varnish apt repository.
  apt_repository:
    repo: "deb https://packagecloud.io/varnishcache/varnish30/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main"
    state: present

- name: Install Varnish.
  apt: name=varnish state=installed

- name: Copy Varnish configuration.
  template:
    src: varnish.j2
    dest: /etc/default/varnish
    owner: root
    group: root
    mode: 0755
