---
vagrantfile-local:
    vm:
        box: 'Ubuntu_14_04__CIBox_VM_provisioned'
        box_url: 'http://cici.ffwua.com/ubuntu14.04provisionedCIBox.box'
        hostname: null
        network:
            private_network: 192.168.56.132
            forwarded_port:
                CocLsFE7aIwA:
                    host: '8081'
                    guest: '80'
                CocLsFE7aIwE:
                    host: '8083'
                    guest: '3306'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '2048'
                    cpus: 2
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            lxc:
                box: 'Ubuntu_14_04__CIBox_VM_provisioned_LXC_version'
                box_url: 'http://cici.ffwua.com/ubuntu14.04provisionedCIBox.lxc.box'
        synced_folder:
            - id: drupal
              source: ./
              target: /var/www
              nfs: 'true'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
