---
- name: Update apt cache.
  apt: 
    update_cache: yes 
    cache_valid_time: 86400

- name: Ensure Apache is installed.
  apt: 
    name: "{{ apache_packages }}"
    state: installed
  #with_items: apache_packages
